name: Sync Release Asset

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Build
        run: |
          npm install --include=dev
          npm run package
      - name: Get version
        id: get-version
        uses: beaconbrigade/package-json-version@v0.3
        with:
          path: .
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            nexus-svg-preview-${{ steps.get-version.outputs.version }}.vsix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
